### ISSUE TITLE
Support for Cloud Witness

### ISSUE THREAD

**Issue by michaelseto** [PowerShell/xFailOverCluster#37]
Hey All!

Are you working on adding a DSCResource for adding a cloud witness for those in Azure?

Thanks!

Michael

**Comment by michaelseto** [comment]
Any updates on this?

**Comment by johlju** [comment]
No work is being done what I know of. But we are happy if you suggest how a resource could work. Should this be added to an existing resource, or is it an entire new resource. Do you have suggestion on the parameters needed?

**Comment by brwilkinson** [comment]
The documentation for the cloud witness is here:
https://docs.microsoft.com/en-us/windows-server/failover-clustering/deploy-cloud-witness 

The following Cmdlet supports setting the cloud witness

FailoverClusters\Set-ClusterQuorum -CloudWitness -AccountName <StorageAccountName> -AccessKey <StorageAccountAccessKey> -Endpoint <servername> 

Parameters should be:
- Endpoint
An optional String, The Default EndPoint should be: core.windows.net

- Cluster
An optional String, The default should leave this off, it will find the cluster on the local machine

- StorageAccountAccessKey
A Mandatory Credential (or String) StorageAccountAccessKey  (only the password from the credential is used as the Key)

- AccountName
A Key String

--------------
The current resource xClusterQuorum could likely not just be extended, by adding CloudWitness to the Type. (Since the parameters don't match, since the key would not fit on the current Types)
[Type = [string]{ CloudWitness | DiskOnly | NodeAndDiskMajority | NodeAndFileShareMajority | NodeMajority }]

So  new resource would most likely be required:

xClusterQuorumCloudWitness [String] #ResourceName
{
      AccountName = [String]
      [EndPoint = [String]]
      StorageAccountAccessKey = [Credential]
}

**Comment by johlju** [comment]
@brwilkinson Thanks for that detailed information. Agree that this suits best as a new resource.

To all: Any takers making this resource? 😄

**Comment by flouwers** [comment]
Hello !
I made some adaptation on a local branch and implemented this functionality.
How can I publish this ?

**Comment by johlju** [comment]
@brwilkinson do you have any thoughts on PR #153?
